### ISSUE TITLE
Errors in GetEEJunct

### ISSUE THREAD

**Issue by lcscs12345** [mevers/RNAModR#2]
`GetEEJunct(refGenome = "hg38", filter = "CDS")`
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘psetdiff’ for signature ‘"GRangesList", "GRangesList"’

**Comment by mevers** [comment]
See [here](https://github.com/mevers/RNAModR/issues/1#issuecomment-279123716).

**Comment by lcscs12345** [comment]
After fixing the issue here (https://github.com/mevers/RNAModR/issues/1), I managed to get BuildTx running. However GetEEJunct function is not working.

**Comment by mevers** [comment]
The script from the [paper's supplements](http://biorxiv.org/content/biorxiv/early/2016/10/10/080051.full.pdf) should work. The above error you got should have been a result of `BuildTx(...)` failing, and has been fixed in [commit 5a4a81b](https://github.com/mevers/RNAModR/commit/5a4a81b6e58e2e1b0360059011dfa070ecc8f739).

I will close this issue; please re-open if the issue persists.
