### ISSUE TITLE
Plotting errors

### ISSUE THREAD

**Issue by lcscs12345** [mevers/RNAModR#3]
`> PlotSpatialEnrichment(posSites, negSites, binWidth = 20, posMax = 1000)`
Error in locNeg[[i]]$REGION_TXWIDTH - locNeg[[i]]$TXSTART : 
  non-numeric argument to binary operator

`> PlotOverlap(posSites, negSites)`
Error in .normargSEW0(start, "start") : 
  'start' must be a numeric vector (or NULL)

`> PlotGC(posSites, negSites, flank = 10)`
Error in rowSums(nucFreq[, c(2, 3)]) : 
  'x' must be an array of at least two dimensions

**Comment by mevers** [comment]
See [here](https://github.com/mevers/RNAModR/issues/1#issuecomment-279123716).

**Comment by lcscs12345** [comment]
I followed the scripts in the supplementary information (http://biorxiv.org/content/early/2016/10/10/080051).
Other plotting functions are working except those three.

**Comment by mevers** [comment]
The script from the [paper's supplements](http://biorxiv.org/content/biorxiv/early/2016/10/10/080051.full.pdf) should work. The above error you got should have been a result of `BuildTx(...)` failing, and has been fixed in [commit 5a4a81b](https://github.com/mevers/RNAModR/commit/5a4a81b6e58e2e1b0360059011dfa070ecc8f739).

I will close this issue; please re-open if the issue persists.
