### ISSUE TITLE
GetEEJunct and PlotRelDistDistribution error

### ISSUE THREAD

**Issue by Zhanghena** [mevers/RNAModR#4]
Hi,

I'm not sure about how to use the GetEEJunct and PlotRelDistDistribution funtions.

I test this using the system file miCLIP_m6A_Linder2015_hg38.bed and bsRNAseq_m5C_Squires2012_hg38.bed. And the transcriptome data was downloaded from https://drive.google.com/file/d/0B5_hfxBdKWHRVlBCTUlSazJfaWs/view

Codes:
source("http://www.bioconductor.org/biocLite.R")
biocLite(c("AnnotationDbi", "beanplot", "Biostrings", "GenomeInfoDb", "GenomicFeatures", "GenomicRanges", "gplots", "RSQLite",    "rtracklayer"))

biocLite(c("BSgenome.Hsapiens.UCSC.hg38", "org.Hs.eg.db"))

if (!require("devtools")) install.packages("devtools"); devtools::install_github("mevers/RNAModR", build_vignettes = FALSE)

# Load the library.
library(RNAModR)
library(RMariaDB)

# Build reference transcriptome.
# This might take a few minutes.
#BuildTx("hg38")

bedFile <- system.file("extdata", "miCLIP_m6A_Linder2015_hg38.bed", package = "RNAModR")
sites <- ReadBED(bedFile)
posSites <- SmartMap(sites , id= "m6A" ,refGenome = "hg38" )

bedFile <- system.file("extdata",
                       "bsRNAseq_m5C_Squires2012_hg38.bed",
                       package = "RNAModR")
sites <- ReadBED(bedFile)
m5Csites <- SmartMap(sites, id= "m5C" ,refGenome = "hg38" )

Error:
PlotRelDistDistribution(posSites,miRNA)

Error: gr1 is not an object of type GRangesList.

junction <- GetEEJunct(refGenome = "hg38", filter = "CDS")
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘psetdiff’ for signature ‘"CompressedGRangesList", "GRangesList"’

Please have a look. Thank you.

**Comment by mevers** [comment]
Hi @Zhanghena .

Thanks for reporting this and apologies for the delay. The new version `RNAModR_0.1.1` should have fixed the issue in `PlotRelDistDistribution` and `PlotRelDistEnrichment`.

The error was due to some [major changes in `GenomicRanges`](https://github.com/Bioconductor/GenomicRanges/blob/master/NEWS), specifically the introduction of the new `CompressedGRangesList` class as a replacement for the `GRangesList` class in version 1.32.0. This meant that critical class checks in RNAModR failed.

The issue in `GetEEJunct` seems to be an issue with `GenomicRanges` where `psetdiff`/`setdiff` hasn't been updated to allow for the new `CompressedGRangesList` inputs. I am still investigating how to work around this.
